schema_version: "0.10.0"
id: "business-frw-02a"
label: "Business FRW-02A"
kind: "firewall"
site: "Central Office"
environment: "Central Office Security"
zone: "Business IT Perimeter"
role: "High-availability stateful policy enforcement member"
summary: "Enforces default-deny policy between the public DMZ and internal Business IT."
lifecycle: "design"
tags: []
render:
  - view: "office/it-dmz"
    node: "business-firewall"
    mode: "any"
  - view: "office/business-it"
    node: "frw-02"
    mode: "any"
interfaces:
  - id: "outside"
    hardware: "ethernet-rj45"
    mac_address: "02:00:00:25:02:01"
    state:
      administrative: "up"
      initial_operational: "up"
    settings:
      speed_mbps: 1000
      duplex: "full"
      mtu: 1500
    mode: "routed"
    addresses:
      - "172.16.10.3/24"
    vlans:
      - 10
  - id: "inside"
    hardware: "ethernet-rj45"
    mac_address: "02:00:00:25:02:02"
    state:
      administrative: "up"
      initial_operational: "up"
    settings:
      speed_mbps: 1000
      duplex: "full"
      mtu: 1500
    mode: "routed"
    addresses:
      - "10.255.0.6/30"
    vlans: []
behavior:
  family: "stateful-firewall"
  stateful: true
  default_action: "deny"
  zones:
    - interface: "outside"
      name: "public-dmz"
    - interface: "inside"
      name: "business-it"
  routes:
    - destination: "172.16.10.0/24"
      next_hop: null
      interface: "outside"
    - destination: "10.255.0.4/30"
      next_hop: null
      interface: "inside"
    - destination: "10.10.80.0/24"
      next_hop: "10.255.0.5"
      interface: "inside"
  rules:
    - name: "permit-web-gateway-to-application-https"
      action: "permit"
      source_zone: "public-dmz"
      destination_zone: "business-it"
      source: "172.16.10.2/32"
      destination: "10.10.80.10/32"
      service: "https"
