schema_version: "0.9.0"
id: "business-frw-01a"
label: "Business FRW-01A"
kind: "firewall"
site: "Central Office"
environment: "Central Office Security"
zone: "Public DMZ Perimeter"
role: "High-availability stateful policy enforcement member"
summary: "Enforces default-deny policy between enterprise edge transit and the public DMZ."
lifecycle: "design"
tags: []
render:
  - view: "customer/public-web-path"
    node: "business-firewall"
    mode: "any"
  - view: "office/it-dmz"
    node: "perimeter-firewall"
    mode: "any"
interfaces:
  - id: "outside"
    hardware: "ethernet-rj45"
    mac_address: "02:00:00:30:01:03"
    state:
      administrative: "up"
      initial_operational: "up"
    settings:
      speed_mbps: 1000
      duplex: "full"
      mtu: 1500
    mode: "routed"
    addresses:
      - "10.255.0.2/30"
    vlans:
      - 1
  - id: "dmz"
    hardware: "ethernet-rj45"
    mac_address: "02:00:00:30:01:04"
    state:
      administrative: "up"
      initial_operational: "up"
    settings:
      speed_mbps: 1000
      duplex: "full"
      mtu: 1500
    mode: "routed"
    addresses:
      - "172.16.10.1/24"
    vlans:
      - 10
behavior:
  family: "stateful-firewall"
  stateful: true
  default_action: "deny"
  zones:
    - interface: "outside"
      name: "internet-transit"
    - interface: "dmz"
      name: "public-dmz"
  routes:
    - destination: "172.16.10.0/24"
      next_hop: null
      interface: "dmz"
    - destination: "10.255.0.0/30"
      next_hop: null
      interface: "outside"
    - destination: "0.0.0.0/0"
      next_hop: "10.255.0.1"
      interface: "outside"
  rules:
    - name: "permit-public-https"
      action: "permit"
      source_zone: "internet-transit"
      destination_zone: "public-dmz"
      source: "any"
      destination: "172.16.10.2/32"
      service: "https"
