import type { Component } from "svelte";
import {
  Boxes,
  CircleCheck,
  CircleDotDashed,
  Cpu,
  Database,
  Droplets,
  Eye,
  Factory,
  Fan,
  FileCheck,
  Flame,
  Gauge,
  Globe2,
  Joystick,
  MonitorCog,
  Network,
  PackageCheck,
  Paintbrush,
  PanelsTopLeft,
  Router,
  Bot,
  ScanSearch,
  ServerCog,
  ShieldCheck,
  Snowflake,
  Thermometer,
  Truck,
  Wind,
} from "@lucide/svelte";
import type { ProcessIconKey } from "./process-model";

export const processIconByKey: Record<ProcessIconKey, Component<any>> = {
  boxes: Boxes,
  "check-circle": CircleCheck,
  cpu: Cpu,
  database: Database,
  droplets: Droplets,
  eye: Eye,
  factory: Factory,
  fan: Fan,
  "file-check": FileCheck,
  flame: Flame,
  gauge: Gauge,
  globe: Globe2,
  joystick: Joystick,
  monitor: MonitorCog,
  network: Network,
  package: PackageCheck,
  paintbrush: Paintbrush,
  "remote-io": PanelsTopLeft,
  router: Router,
  robot: Bot,
  scan: ScanSearch,
  server: ServerCog,
  shield: ShieldCheck,
  snowflake: Snowflake,
  thermometer: Thermometer,
  truck: Truck,
  valve: CircleDotDashed,
  wind: Wind,
};
