import {
  Building2,
  Database,
  Laptop,
  Network,
  Phone,
  Printer,
  Server,
  ShieldCheck,
  Users,
  Wifi,
} from "@lucide/svelte";
import type { OfficeNode } from "./types";

export const businessItNodes: OfficeNode[] = [
  {
    id: "frw-02",
    label: "Business FRW-02A / 02B",
    role: "High-availability upstream security boundary toward the public IT DMZ",
    area: "IT perimeter",
    address: "10.255.0.6/30",
    facts: ["Inside Ethernet0/0", "Default route through the public DMZ"],
    accent: "#9e3f2f",
    icon: ShieldCheck,
    physical: { x: 70, y: 280 },
    logical: { x: 35, y: 390 },
  },
  {
    id: "it-core",
    label: "Business IT-CORE-SW-01 / 02",
    role: "Redundant Layer 3 core and gateway role for internal security zones",
    area: "Network core",
    address: "VLAN gateway VIPs 10.10.20.1–90.1",
    facts: [
      "Redundant routed transit to FRW-02A/02B",
      "No user traffic is carried on the native VLAN",
      "Inter-zone traffic is deny by default and explicitly permitted",
    ],
    accent: "#267168",
    icon: Network,
    physical: { x: 290, y: 280 },
    logical: { x: 285, y: 390 },
  },
  {
    id: "server-switch",
    label: "Business IT-SRV-SW-01 / 02",
    role: "Redundant access switching for infrastructure and application zones",
    area: "Server access",
    address: "VLANs 20, 70, 80, 90, 999",
    facts: ["Dual uplinks to the core pair", "Management uses VLAN 70"],
    accent: "#3567a6",
    icon: Network,
    physical: { x: 525, y: 190 },
    logical: { x: 590, y: 155 },
  },
  {
    id: "server-fleet",
    label: "Internal Service Clusters",
    role: "Infrastructure, application, data, transfer, monitoring, backup, and time services",
    area: "VLANs 20, 80, 90",
    address: "Infrastructure, application, and data VIPs",
    facts: [
      "Dedicated DNS, DHCP, PKI, and primary/secondary time sources",
      "Application/API services are separated from data services",
      "Managed transfer, monitoring, backup, and recovery roles are defined",
      "Public gateways reach only named application VIPs",
    ],
    accent: "#51704c",
    icon: Database,
    physical: { x: 790, y: 150 },
    logical: { x: 875, y: 85 },
  },
  {
    id: "voice-gateway",
    label: "Business IT-VOICE-GW-01",
    role: "Enterprise voice call-control gateway",
    area: "VLAN 20 · IT_SERVERS",
    address: "10.10.20.50/24",
    facts: ["Voice registration and call control", "Uses the dedicated enterprise time service", "Attached through the server access pair"],
    accent: "#6a5c91",
    icon: Phone,
    physical: { x: 790, y: 285 },
    logical: { x: 875, y: 230 },
  },
  {
    id: "user-switch",
    label: "Business IT-USR-SW-01 / 02",
    role: "Redundant employee access switching role",
    area: "User access",
    address: "VLANs 30, 70, 999",
    facts: ["Redundant uplinks to the core pair", "Management uses VLAN 70"],
    accent: "#3567a6",
    icon: Network,
    physical: { x: 525, y: 520 },
    logical: { x: 590, y: 390 },
  },
  {
    id: "user-pcs",
    label: "Business IT-USR-PC-01–04",
    role: "Representative managed employee workstations",
    area: "VLAN 30 · IT_USERS",
    address: "DHCP from 10.10.30.100",
    facts: ["Fa0/1–4 on USR-SW-01", "Internal DNS 10.10.20.10"],
    accent: "#426d9d",
    icon: Users,
    physical: { x: 790, y: 520 },
    logical: { x: 875, y: 390 },
  },
  {
    id: "service-switch",
    label: "Business IT-SVC-SW-01 / 02",
    role: "Redundant access switching for voice, printers, and wireless",
    area: "Office services",
    address: "VLANs 40, 50, 70, 999",
    facts: ["Redundant uplinks to the core pair", "Management uses VLAN 70"],
    accent: "#3567a6",
    icon: Network,
    physical: { x: 525, y: 680 },
    logical: { x: 590, y: 625 },
  },
  {
    id: "phone",
    label: "Business IT-PHONE-01",
    role: "Registered enterprise voice endpoint",
    area: "VLAN 40 · IT_VOICE",
    address: "DHCP from 10.10.40.100",
    facts: ["SVC-SW Fa0/1 voice VLAN 40", "Extension 2001", "Option 150 points to 10.10.20.50"],
    accent: "#6a5c91",
    icon: Phone,
    physical: { x: 790, y: 650 },
    logical: { x: 875, y: 555 },
  },
  {
    id: "printer",
    label: "Business IT-PRN-01",
    role: "Shared office printer",
    area: "VLAN 50 · IT_PRINTERS",
    address: "10.10.50.10/24",
    facts: ["SVC-SW Fa0/2", "Gateway 10.10.50.1"],
    accent: "#7a6546",
    icon: Printer,
    physical: { x: 1010, y: 705 },
    logical: { x: 875, y: 700 },
  },
  {
    id: "guest-access",
    label: "Guest Wireless",
    role: "Isolated guest WLAN and representative unmanaged client",
    area: "VLAN 60 · IT_GUEST",
    address: "Business-Guest · DHCP from 10.10.60.100",
    facts: [
      "Access points use a separate management network",
      "Client isolation is enabled",
      "Guest traffic is limited to filtered Internet egress",
    ],
    accent: "#b65034",
    icon: Wifi,
    physical: { x: 80, y: 640 },
    logical: { x: 1190, y: 150 },
  },
  {
    id: "admin-pc",
    label: "Business IT-PAW-01",
    role: "Privileged access workstation for approved administration",
    area: "VLAN 70 · IT_MANAGEMENT",
    address: "10.10.70.30/24",
    facts: ["Dedicated management source role", "MFA and device posture required", "No general productivity use"],
    accent: "#267168",
    icon: Laptop,
    physical: { x: 1080, y: 210 },
    logical: { x: 1190, y: 350 },
  },
  {
    id: "network-controller",
    label: "Business IT-NET-CTRL-01",
    role: "Central network-management controller",
    area: "VLAN 70 · IT_MANAGEMENT",
    address: "10.10.70.20/24",
    facts: ["Management VLAN only", "AAA, configuration backup, and approved automation", "No public service exposure"],
    accent: "#267168",
    icon: Server,
    physical: { x: 1300, y: 330 },
    logical: { x: 1450, y: 440 },
  },
  {
    id: "frw-03",
    label: "Business FRW-03A / 03B",
    role: "High-availability boundary from Business IT to the Factory OT DMZ",
    area: "OT security handoff",
    address: "Canonical addressing pending",
    facts: [
      "Only intended Business IT-to-OT DMZ boundary",
      "Reached through the Operations Intelligence policy path",
      "Conduits require explicit source, destination, service, and purpose",
    ],
    accent: "#9e3f2f",
    icon: ShieldCheck,
    physical: { x: 1535, y: 360 },
    logical: { x: 1190, y: 650 },
  },
  {
    id: "ot-dmz-handoff",
    label: "OT DMZ Handoff",
    role: "Adjacent Level 3.5 environment; no direct path to OT",
    area: "Adjacent environment",
    address: "Canonical addressing pending",
    facts: ["Terminates in the OT DMZ", "Does not bypass the OT-side firewall"],
    accent: "#51704c",
    icon: Building2,
    physical: { x: 1535, y: 580 },
    logical: { x: 1480, y: 650 },
  },
];
