import {
  Building2,
  Cloud,
  Network,
  RadioTower,
  Router,
  Server,
  ShieldCheck,
} from "@lucide/svelte";
import type { OfficeNode } from "./types";

export const itDmzNodes: OfficeNode[] = [
  {
    id: "wan-02",
    label: "WAN-02A / 02B",
    role: "Diverse business-facing provider circuits",
    area: "Provider handoff",
    address: "192.0.2.0/24",
    facts: ["Independent carrier paths are required", "No enterprise routing function at the access handoff"],
    accent: "#6a5c91",
    icon: Cloud,
    physical: { x: 35, y: 400 },
    logical: { x: 35, y: 400 },
  },
  {
    id: "business-modem",
    label: "Business INET-CPE-01 / 02",
    role: "Provider-managed access CPE at the business demarcation",
    area: "WAN demarcation",
    address: "No Layer 3 address",
    facts: ["Independent access circuits", "Customer handoffs to the enterprise edge pair"],
    accent: "#7a6546",
    icon: RadioTower,
    physical: { x: 250, y: 400 },
    logical: { x: 250, y: 400 },
  },
  {
    id: "business-edge",
    label: "Business EDGE-RTR-01 / 02",
    role: "Redundant Internet edge and public static NAT role",
    area: "Enterprise edge",
    address: "192.0.2.2/24 · 10.255.0.1/30",
    facts: [
      "192.0.2.10 maps to 172.16.10.2",
      "Default route to 192.0.2.1",
      "DMZ route through 10.255.0.2",
    ],
    accent: "#b65034",
    icon: Router,
    physical: { x: 465, y: 400 },
    logical: { x: 465, y: 400 },
  },
  {
    id: "perimeter-firewall",
    label: "Business FRW-01A / 01B",
    role: "High-availability policy boundary between edge transit and public DMZ",
    area: "Perimeter security",
    address: "10.255.0.2/30 · 172.16.10.1/24",
    facts: [
      "Independent outside and public DMZ zones",
      "Inbound policy permits HTTPS to the published gateway VIP",
      "HTTP is redirect-only when explicitly enabled",
    ],
    accent: "#9e3f2f",
    icon: ShieldCheck,
    physical: { x: 690, y: 400 },
    logical: { x: 690, y: 400 },
  },
  {
    id: "dmz-switch",
    label: "Business IT-DMZ-SW-01 / 02",
    role: "Redundant public DMZ switching role",
    area: "Public DMZ",
    address: "VLAN 10 · PUBLIC_DMZ",
    facts: [
      "Independent links to FRW-01A/01B",
      "Dual-attached web gateway tier",
      "Independent links to FRW-02A/02B",
    ],
    accent: "#3567a6",
    icon: Network,
    physical: { x: 900, y: 400 },
    logical: { x: 930, y: 400 },
  },
  {
    id: "public-web",
    label: "Business WEB-GW-01 / 02",
    role: "Reverse proxy, TLS termination, and web application firewall tier",
    area: "Published service",
    address: "172.16.10.2/24 · public 192.0.2.10",
    facts: [
      "HTTPS terminates at the DMZ gateway VIP",
      "HTTP is redirect-only when enabled",
      "Only named internal application dependencies are proxied",
    ],
    accent: "#51704c",
    icon: Server,
    physical: { x: 1160, y: 260 },
    logical: { x: 1210, y: 260 },
  },
  {
    id: "business-firewall",
    label: "Business FRW-02A / 02B",
    role: "High-availability downstream boundary from the public DMZ to Business IT",
    area: "IT handoff",
    address: "172.16.10.3/24 · 10.255.0.6/30",
    facts: [
      "Ethernet0/1 faces the public DMZ",
      "Ethernet0/0 faces Business IT",
      "No unsolicited DMZ-to-IT access by default",
    ],
    accent: "#9e3f2f",
    icon: ShieldCheck,
    physical: { x: 1160, y: 545 },
    logical: { x: 1210, y: 545 },
  },
  {
    id: "business-core-handoff",
    label: "Business IT Core Handoff",
    role: "Adjacent routed handoff into the internal Business IT environment",
    area: "Adjacent environment",
    address: "10.255.0.5/30",
    facts: ["FRW-02A/02B inside next hop", "Detailed in the Business IT environment"],
    accent: "#267168",
    icon: Building2,
    physical: { x: 1510, y: 545 },
    logical: { x: 1500, y: 545 },
  },
];
