import {
  Building2,
  Database,
  Factory,
  FileCheck,
  Globe2,
  Network,
  ShieldCheck,
  Users,
} from "@lucide/svelte";
import type { OfficeNode } from "./types";

export const operationsIntelligenceNodes: OfficeNode[] = [
  {
    id: "business-it-source",
    label: "Business IT",
    role: "Enterprise source for approved users, identity, and governance workflows",
    area: "Enterprise handoff",
    address: "Business IT management networks",
    facts: [
      "No direct route to controllers",
      "Administrative access requires named users and managed devices",
    ],
    accent: "#3567a6",
    icon: Building2,
    physical: { x: 30, y: 400 },
    logical: { x: 30, y: 400 },
  },
  {
    id: "identity-policy",
    label: "Identity & Policy Services",
    role: "Central identity, authorization, device posture, and policy decision services",
    area: "Enterprise governance",
    address: "Canonical addressing pending",
    facts: [
      "Policy engine and policy administrator roles",
      "MFA and phishing-resistant authentication",
      "Managed-device posture",
      "Maintenance-window and work-order context",
      "Resource-side enforcement points apply the decision",
    ],
    accent: "#6a5c91",
    icon: ShieldCheck,
    physical: { x: 270, y: 180 },
    logical: { x: 270, y: 180 },
  },
  {
    id: "central-noc",
    label: "Central NOC",
    role: "Network architecture, configuration governance, availability, and change coordination",
    area: "Network operations",
    address: "Canonical addressing pending",
    facts: [
      "Owns enterprise and inter-site network decisions",
      "Changes follow approval and staging",
      "No direct interactive controller access",
    ],
    accent: "#267168",
    icon: Network,
    physical: { x: 520, y: 180 },
    logical: { x: 520, y: 180 },
  },
  {
    id: "central-soc",
    label: "Central SOC",
    role: "Security monitoring, investigation, and incident coordination",
    area: "Security operations",
    address: "Canonical addressing pending",
    facts: [
      "Consumes approved security telemetry",
      "Coordinates response with factory OT operations",
      "Monitoring is not a process forwarding dependency",
    ],
    accent: "#9e3f2f",
    icon: ShieldCheck,
    physical: { x: 520, y: 545 },
    logical: { x: 520, y: 545 },
  },
  {
    id: "analytics-platform",
    label: "Process Analytics Platform",
    role: "Enterprise analysis of selected production, quality, energy, and maintenance data",
    area: "Operations analytics",
    address: "Canonical addressing pending",
    facts: [
      "Reads brokered or replicated data",
      "Does not query the primary OT historian directly",
      "Analytics output is advisory until approved",
    ],
    accent: "#51704c",
    icon: Database,
    physical: { x: 850, y: 180 },
    logical: { x: 850, y: 180 },
  },
  {
    id: "process-analysts",
    label: "Process Analysis Workstations",
    role: "Engineering and business analysis of process performance and product quality",
    area: "Analysis workspace",
    address: "Managed enterprise endpoints",
    facts: [
      "Uses approved datasets and dashboards",
      "Cannot issue direct control commands",
      "Recommendations enter the governed change workflow",
    ],
    accent: "#426d9d",
    icon: Users,
    physical: { x: 1100, y: 180 },
    logical: { x: 1100, y: 180 },
  },
  {
    id: "change-staging",
    label: "Change Approval & Staging",
    role: "Review, approval, scanning, signing, and staging of authorized changes",
    area: "Governed change",
    address: "Canonical addressing pending",
    facts: [
      "Separates analysis from implementation",
      "Produces auditable approved packages",
      "Factory personnel retain execution authority",
    ],
    accent: "#7a6546",
    icon: FileCheck,
    physical: { x: 850, y: 545 },
    logical: { x: 850, y: 545 },
  },
  {
    id: "factory-conduit",
    label: "Encrypted Factory Conduit",
    role: "Authenticated inter-site transport to the factory security perimeter",
    area: "Inter-site WAN",
    address: "Canonical transport pending",
    facts: [
      "Carries only named data and administrative workflows",
      "WAN loss does not stop local factory operation",
      "Factory-local firewalls remain authoritative",
    ],
    accent: "#6a5c91",
    icon: Globe2,
    physical: { x: 1325, y: 545 },
    logical: { x: 1280, y: 545 },
  },
  {
    id: "factory-dmz-target",
    label: "Factory OT DMZ",
    role: "Adjacent factory-local security and exchange environment",
    area: "Adjacent environment",
    address: "Factory Level 3.5",
    facts: [
      "Terminates Central Office access locally",
      "Brokers selected OT data outward",
      "No conduit bypasses the OT-side firewall",
    ],
    accent: "#b65034",
    icon: Factory,
    physical: { x: 1550, y: 545 },
    logical: { x: 1550, y: 545 },
  },
];
