import {
  Building2,
  Database,
  FileCheck,
  Globe2,
  Network,
  RadioTower,
  Server,
  ShieldCheck,
} from "@lucide/svelte";
import type { OfficeNode } from "./types";

export const otDmzNodes: OfficeNode[] = [
  {
    id: "business-it-handoff",
    label: "Central Office Conduit",
    role: "Encrypted inter-site transport carrying approved data and administrative workflows",
    area: "Northbound WAN",
    address: "Canonical transport pending",
    facts: [
      "Named Central Office sources only",
      "No direct route to factory OT",
      "Factory-local policy remains authoritative",
    ],
    accent: "#3567a6",
    icon: Building2,
    physical: { x: 30, y: 400 },
    logical: { x: 30, y: 400 },
  },
  {
    id: "north-firewall",
    label: "Business FRW-03A / 03B",
    role: "Northbound HA policy boundary between Business IT and the OT DMZ",
    area: "IT-side boundary",
    address: "Canonical addressing pending",
    facts: ["Synchronized HA policy role", "Independent from OT FRW-01", "Deny by default"],
    accent: "#9e3f2f",
    icon: ShieldCheck,
    physical: { x: 265, y: 400 },
    logical: { x: 265, y: 400 },
  },
  {
    id: "dmz-switch-pair",
    label: "OT-DMZ-SW-01 / 02",
    role: "Redundant Layer 2 attachment without unrestricted inter-subzone routing",
    area: "DMZ switching",
    address: "Subzone VLANs pending",
    facts: [
      "Independent firewall and service attachment paths",
      "Explicit loop-avoidance or multi-chassis design required",
      "Access, exchange, and monitoring remain separate",
    ],
    accent: "#267168",
    icon: Network,
    physical: { x: 500, y: 400 },
    logical: { x: 500, y: 400 },
  },
  {
    id: "jump-service",
    label: "OT-DMZ-JUMP-SRV-01 / 02",
    role: "Controlled administrative access and session termination",
    area: "Access subzone",
    address: "Canonical addressing pending",
    facts: [
      "Separate authenticated session into Level 3",
      "No general browsing, email, or direct Internet",
      "Time-bound and recorded privileged access",
    ],
    accent: "#426d9d",
    icon: Server,
    physical: { x: 800, y: 160 },
    logical: { x: 800, y: 135 },
  },
  {
    id: "historian-replica",
    label: "OT-DMZ-HIST-REPLICA-01",
    role: "Business-facing replica of selected OT historian data",
    area: "Exchange subzone",
    address: "Canonical addressing pending",
    facts: [
      "IT consumers do not query the primary OT historian",
      "One-way or brokered exchange policy pending",
    ],
    accent: "#51704c",
    icon: Database,
    physical: { x: 800, y: 370 },
    logical: { x: 800, y: 315 },
  },
  {
    id: "transfer-service",
    label: "OT-DMZ-XFER-SRV-01",
    role: "Managed file transfer and update staging",
    area: "Exchange subzone",
    address: "Canonical addressing pending",
    facts: ["Staged and scanned files", "Approval and direction are explicit", "All transfers are audited"],
    accent: "#7a6546",
    icon: FileCheck,
    physical: { x: 800, y: 515 },
    logical: { x: 800, y: 495 },
  },
  {
    id: "monitoring",
    label: "OT-DMZ-MON-01",
    role: "Security telemetry collector and monitoring management role",
    area: "Monitoring subzone",
    address: "Canonical addressing pending",
    facts: ["Not an inline forwarding hop", "Capture and management paths are distinct"],
    accent: "#6a5c91",
    icon: Server,
    physical: { x: 800, y: 700 },
    logical: { x: 770, y: 675 },
  },
  {
    id: "passive-sensors",
    label: "OT-SENSOR-*",
    role: "Passive sensors on defined SPAN or TAP sources",
    area: "Monitoring subzone",
    address: "Out-of-band capture",
    facts: ["Process traffic never depends on sensor forwarding", "Active probing requires explicit approval"],
    accent: "#6a5c91",
    icon: RadioTower,
    physical: { x: 970, y: 700 },
    logical: { x: 970, y: 675 },
  },
  {
    id: "south-firewall",
    label: "OT FRW-01A / 01B",
    role: "Independent southbound HA policy boundary into Level 3 OT",
    area: "OT-side boundary",
    address: "Canonical addressing pending",
    facts: [
      "Permission at FRW-03 does not imply permission here",
      "Named conduits only",
      "Failover preserves deny-by-default policy",
    ],
    accent: "#9e3f2f",
    icon: ShieldCheck,
    physical: { x: 1285, y: 400 },
    logical: { x: 1285, y: 400 },
  },
  {
    id: "level-three",
    label: "Level 3 OT Engineering",
    role: "Adjacent OT core and engineering zone",
    area: "Southbound environment",
    address: "Canonical addressing pending",
    facts: [
      "OT-ENG-WS-01 resides here, not in the DMZ",
      "Named controller access crosses cell or area policy",
    ],
    accent: "#51704c",
    icon: Globe2,
    physical: { x: 1550, y: 400 },
    logical: { x: 1550, y: 400 },
  },
];
